spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/qipai_game


  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
        bindings:
          notice:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          gameServer:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          mail:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          gameDataReport:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          memberrightsconfiguration:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          ruianGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          fangpaoGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          wenzhouGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          dianpaoGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          wenzhouShuangkouGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          chayuanShuangkouGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          doudizhuGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          daboluoGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          paodekuaiGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          memberLoginRecord:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          roomManage:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          gameDianpaomjResult:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          gameFangpaomjResult:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          gameRuianmjResult:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          gameWenzhoumjResult:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          gameWenzhouskResult:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          gameChayuanskResult:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          gameDoudizhuResult:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          gameDaboluoResult:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          gamePaodekuaiResult:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
                  
      bindings:
        notice:
          destination: notice
          contentType: application/json
          producer:
            partitionCount: 1
        gameServer:
          destination: gameServer
          contentType: application/json
          producer:
            partitionCount: 1
        ruianGameRoom:
          destination: ruianGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        fangpaoGameRoom:
          destination: fangpaoGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        wenzhouGameRoom:
          destination: wenzhouGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        dianpaoGameRoom:
          destination: dianpaoGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        wenzhouShuangkouGameRoom:
          destination: wenzhouShuangkouGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        chayuanShuangkouGameRoom:
          destination: chayuanShuangkouGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        doudizhuGameRoom:
          destination: doudizhuGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        daboluoGameRoom:
          destination: daboluoGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        paodekuaiGameRoom:
          destination: paodekuaiGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        memberGolds:
          destination: memberGolds
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json    
        members:
          destination: members
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        mail:
          destination: mail
          contentType: application/json
          producer:
            partitionCount: 1
        gameDataReport:
          destination: gameDataReport
          contentType: application/json
          producer:
            partitionCount: 1
        memberrightsconfiguration:
          destination: memberrightsconfiguration
          contentType: application/json
          producer:
            partitionCount: 1
        ruianMajiangGame:
          destination: ruianMajiangGame
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        ruianMajiangResult:
          destination: ruianMajiangResult
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        fangpaoMajiangGame:
          destination: fangpaoMajiangGame
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        fangpaoMajiangResult:
          destination: fangpaoMajiangResult
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        wenzhouMajiangGame:
          destination: wenzhouMajiangGame
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        wenzhouMajiangResult:
          destination: wenzhouMajiangResult
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        dianpaoMajiangGame:
          destination: dianpaoMajiangGame
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        dianpaoMajiangResult:
          destination: dianpaoMajiangResult
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        wenzhouShuangkouGame:
          destination: wenzhouShuangkouGame
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        wenzhouShuangkouResult:
          destination: wenzhouShuangkouResult
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        chayaunShuangkouGame:
          destination: chayuanShuangkouGame
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        chayuanShuangkouResult:
          destination: chayuanShuangkouResult
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        doudizhuGame:
          destination: doudizhuGame
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        doudizhuResult:
          destination: doudizhuResult
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        daboluoGame:
          destination: daboluoGame
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        daboluoResult:
          destination: daboluoResult
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        paodekuaiGame:
          destination: paodekuaiGame
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        paodekuaiResult:
          destination: paodekuaiResult
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        gameServerManager:
          destination: gameServer
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        signInPrize:
          destination: signInPrize
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberLoginRecord:
          destination: memberLoginRecord
          contentType: application/json
          producer:
            partitionCount: 1
        memberLoginLimitRecord:
          destination: memberLoginLimitRecord
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        roomManage:
          destination: roomManage
          contentType: application/json
          producer:
            partitionCount: 1
        gameDianpaomjResult:
          destination: gameDianpaomjResult
          contentType: application/json
          producer:
            partitionCount: 1
        gameFangpaomjResult:
          destination: gameFangpaomjResult
          contentType: application/json
          producer:
            partitionCount: 1
        gameRuianmjResult:
          destination: gameRuianmjResult
          contentType: application/json
          producer:
            partitionCount: 1
        gameWenzhoumjResult:
          destination: gameWenzhoumjResult
          contentType: application/json
          producer:
            partitionCount: 1
        gameWenzhouskResult:
          destination: gameWenzhouskResult
          contentType: application/json
          producer:
            partitionCount: 1
        gameChayuanskResult:
          destination: gameChayuanskResult
          contentType: application/json
          producer:
            partitionCount: 1
        gameDoudizhuResult:
          destination: gameDoudizhuResult
          contentType: application/json
          producer:
            partitionCount: 1
        gameDaboluoResult:
          destination: gameDaboluoResult
          contentType: application/json
          producer:
            partitionCount: 1
        gamePaodekuaiResult:
          destination: gamePaodekuaiResult
          contentType: application/json
          producer:
            partitionCount: 1

  application:
    name: qipai-game
server:
  port: 83
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  #instance:
    #prefer-ip-address: true
    #instance-id: http://172.16.21.51:83
websocket:
  #url: ws://47.96.20.47:83/hall
  url: ws://192.168.0.156:83/hall
filepath:
  snapshotFileBasePath: /data/app/qipai_game/snapshot
  jFileBasePath: /data/app/qipai_game/journal