spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/qipai_game
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
        bindings:
          notice:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          gameServer:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          mail:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          memberrightsconfiguration:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
      bindings:
        notice:
          destination: notice
          contentType: application/json
          producer:
            partitionCount: 1
        gameServer:
          destination: gameServer
          contentType: application/json
          producer:
            partitionCount: 1
        members:
          destination: members
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        mail:
          destination: mail
          contentType: application/json
          producer:
            partitionCount: 1
        memberrightsconfiguration:
          destination: memberrightsconfiguration
          contentType: application/json
          producer:
            partitionCount: 1
  application:
    name: qipai-game
server:
  port: 83
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
websocket:
  url: ws://192.168.0.9:83/hall