spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/qipai_game
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
        bindings:
          notice:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          gameServer:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          mail:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          memberrightsconfiguration:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          ruianGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          fangpaoGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          wenzhouGameRoom:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
      bindings:
        notice:
          destination: notice
          contentType: application/json
          producer:
            partitionCount: 1
        gameServer:
          destination: gameServer
          contentType: application/json
          producer:
            partitionCount: 1
        ruianGameRoom:
          destination: ruianGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        fangpaoGameRoom:
          destination: fangpaoGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        wenzhouGameRoom:
          destination: wenzhouGameRoom
          contentType: application/json
          producer:
            partitionCount: 1
        members:
          destination: members
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        mail:
          destination: mail
          contentType: application/json
          producer:
            partitionCount: 1
        memberrightsconfiguration:
          destination: memberrightsconfiguration
          contentType: application/json
          producer:
            partitionCount: 1
        ruianMajiangGame:
          destination: ruianMajiangGame
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        ruianMajiangResult:
          destination: ruianMajiangResult
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        fangpaoMajiangGame:
          destination: fangpaoMajiangGame
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        fangpaoMajiangResult:
          destination: fangpaoMajiangResult
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        wenzhouMajiangGame:
          destination: wenzhouMajiangGame
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        wenzhouMajiangResult:
          destination: wenzhouMajiangResult
          group: qipai-game
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        
  application:
    name: qipai-game
server:
  port: 83
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
websocket:
  url: ws://192.168.0.134:83/hall
  
filepath:
  snapshotFileBasePath: /usr/local/app/qipai_game/snapshot
  jFileBasePath: /usr/local/app/qipai_game/journal