spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/qipai_game
  application:
    name: qipai-game
server:
  port: 83
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/